name: honeybee
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_audio_query: "0.3.4+2"
  provider: ^4.0.4
  flutter_beautiful_popup: ^1.4.0
  firebase_auth: ^0.15.5+3
  firebase_messaging: ^6.0.15
  firebase_auth_ui: ^1.0.1
  carousel_slider: ^2.1.0
  audioplayers: ^0.14.0
  settings_ui: ^0.2.0
  random_color: ^1.0.3
  device_id: ^0.2.0
  mqtt_client: ^5.6.2
  http: ^0.12.0+4
  sqflite:
  zego_express_engine: ^0.9.3
  social_share_plugin: ^0.3.1+1
  cupertino_icons: ^0.1.2
  video_player: ^0.8.0
  svgaplayer_flutter: ^1.1.0
  wakelock: ^0.1.4+1
  sticky_headers: "^0.1.8"
  flutter_launcher_icons: ^0.7.5
  fluttertoast: ^3.1.3
  google_fonts: ^0.3.9
  swipedetector: ^1.2.0
  webview_flutter: ^0.3.4
  flutter_svg: ^0.17.4
  image_picker: ^0.6.3+4
  flutter_auth_buttons: ^0.8.0
  gradient_app_bar: ^0.0.1
  permission_handler: ^5.0.0+hotfix.1
  shared_preferences: '0.5.3+1'
  font_awesome_flutter: ^8.0.1
  percent_indicator: ^2.1.1+1
  store_redirect: ^1.0.2
  connectivity: ^0.4.8+6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/videos/aeologic_logo.mp4
    - assets/login/BG.jpg
    - assets/login/Logo.png
    - assets/login/Logo_text.png
    - assets/login/Google.png
    - assets/profile/ProfileBG.png
    - assets/profile/Wallet.svg
    - assets/profile/Medal.png
    - assets/profile/diamond.png
    - assets/profile/Bgold.png
    - assets/profile/Medal.svg
    - assets/profile/Writing.svg
    - assets/profile/Statistics.svg
    - assets/profile/Setting.svg
    - assets/profile/Gold.svg
    - assets/profile/Bank.svg
    - assets/profile/Diamond.svg
    - assets/profile/Coin.svg
    - assets/login/Insta.png
    - assets/login/Mobile.png
    - assets/login/Facebook.png
    - assets/login/Twitter.png
    - assets/broadcast/AudioBG.jpg
    - assets/broadcast/menu.png
    - assets/broadcast/chair.png
    - assets/broadcast/mic.png
    - assets/broadcast/tropy.png
    - assets/broadcast/audiocall.png
    - assets/broadcast/Chat.png
    - assets/broadcast/Close.png
    - assets/broadcast/Coin.png
    - assets/broadcast/Gift.png
    - assets/broadcast/Share.png
    - assets/broadcast/Fans.png
    - assets/broadcast/BulletMessage.png
    - assets/broadcast/Send.png
    - assets/broadcast/Gold.png
    - assets/liveroom/games.svg
    - assets/liveroom/pk.svg
    - assets/liveroom/chair.svg
    - assets/liveroom/gallery.svg
    - assets/liveroom/share.png
    - assets/liveroom/music.svg
    - assets/liveroom/heart.svg
    - assets/dashboard/Home.png
    - assets/dashboard/HomeSelected.png
    - assets/dashboard/PKSelected.png
    - assets/dashboard/Profile.png
    - assets/dashboard/ProfileSelected.png
    - assets/dashboard/Toppers.png
    - assets/dashboard/Golive.png
    - assets/dashboard/ToppersSelected.png
    - assets/lady/lady1.jpg
    - assets/lady/lady2.jpg
    - assets/lady/lady3.png
    - assets/lady/lady4.jpg


